- hosts: Swarm
  vars_files:
    - common_vars.yml
  tasks:
    - name: Add Apt key from docker repo
      become: yes
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add docker repo for Stretch
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: Install Docker
      become: yes
      apt: pkg=docker-ce state=present update_cache=true
      notify:
        - Start Docker

    - name: Adding autobot user to group docker
      become: yes
      user:
        name: '{{ node_user }}'
        group: '{{ node_user }}'
        groups: docker,cdrom,sudo,audio,dip,video,plugdev,netdev
        append: yes

    # Make sure all nodes can talk to each other by Hostname
    - name: Update /etc/hosts
      action: template src=templates/hosts.j2 dest=/etc/hosts

  handlers:
    - name: Start Docker
      service: name=docker state=started

# Setup The swarm
- hosts: SwarmMaster
  vars_files:
    - common_vars.yml
  tasks:
    - name: Check for existing swarm
      shell: docker node ls
      register: status_of_swarm
      ignore_errors: true

    - name: Create a new swarm with default parameters
      docker_swarm:
        state: present
      when: status_of_swarm.rc != 0
      notify: Add Manager to Swarm

    # Get the tokens required for the managers and workers
    - name: Get the Manager join-token
      shell: docker swarm join-token --quiet manager
      register: token_for_manager

    - name: Get the worker join-token
      shell: docker swarm join-token --quiet worker
      register: token_for_worker

  handlers:
    - name: Add Manager to Swarm
      shell: "docker swarm join --token '{{ token_for_manager.stdout }}' {{ item }}:2377"
      with_items:
        - node1_ip

# Add workers and managers to swarm
- hosts: Swarm
  tasks:
    - name: Check for existing swarm
      shell: docker node ls
      register: status_of_swarm
      ignore_errors: true

    - name: Add Workers to Swarm
      shell: "docker swarm join --token '{{ token_for_worker.stdout }}' '{{ item }}':2377"
      with_items:
        - node2_ip
        - node3_ip